"""Milo — Template-driven CLI applications for free-threaded Python."""

from __future__ import annotations

_LAZY_IMPORTS = {
    # Types
    "Action": "_types",
    "Key": "_types",
    "SpecialKey": "_types",
    "AppStatus": "_types",
    "RenderTarget": "_types",
    "FieldType": "_types",
    "FieldSpec": "_types",
    "FieldState": "_types",
    "FormState": "_types",
    "Screen": "_types",
    "Transition": "_types",
    "ReducerResult": "_types",
    "Quit": "_types",
    "Call": "_types",
    "Put": "_types",
    "Select": "_types",
    "Fork": "_types",
    "Delay": "_types",
    "Retry": "_types",
    "Timeout": "_types",
    "TryCall": "_types",
    "Race": "_types",
    "All": "_types",
    "Take": "_types",
    "Debounce": "_types",
    "Cmd": "_types",
    "Batch": "_types",
    "Sequence": "_types",
    "TickCmd": "_types",
    "ViewState": "_types",
    "compact_cmds": "_types",
    "BUILTIN_ACTIONS": "_types",
    # Errors
    "MiloError": "_errors",
    "InputError": "_errors",
    "StateError": "_errors",
    "FormError": "_errors",
    "AppError": "_errors",
    "FlowError": "_errors",
    "ConfigError": "_errors",
    "PipelineError": "_errors",
    "PluginError": "_errors",
    "MCPAppError": "_errors",
    "ErrorCode": "_errors",
    "format_error": "_errors",
    "format_render_error": "_errors",
    # State
    "Store": "state",
    "SagaContext": "state",
    "EffectResult": "state",
    "combine_reducers": "state",
    # App
    "App": "app",
    "run": "app",
    "render_html": "app",
    # Flow
    "FlowScreen": "flow",
    "Flow": "flow",
    "FlowState": "flow",
    # Form
    "form": "form",
    "form_reducer": "form",
    "form_schema": "form",
    "make_form_reducer": "form",
    # Help
    "HelpRenderer": "help",
    # Dev
    "DevServer": "dev",
    # Commands (AI-native)
    "CLI": "commands",
    "CommandDef": "commands",
    "CommandSurface": "commands",
    "LazyCommandDef": "commands",
    "InvokeResult": "commands",
    # Groups
    "Group": "groups",
    "GroupDef": "groups",
    "GlobalOption": "commands",
    "RootOptionSpec": "commands",
    # Context
    "ConfirmStrategy": "context",
    "Context": "context",
    "NullOutputSink": "context",
    "OutputSink": "context",
    "get_context": "context",
    "CLIProgress": "context",
    # Config
    "Config": "config",
    "ConfigSpec": "config",
    # Pipeline
    "Pipeline": "pipeline",
    "Phase": "pipeline",
    "PhasePolicy": "pipeline",
    "PhaseLog": "pipeline",
    "PipelineState": "pipeline",
    "PhaseStatus": "pipeline",
    "PipelineViewState": "pipeline",
    "make_detail_reducer": "pipeline",
    "pipeline_to_timeline": "pipeline",
    "set_active_pipeline": "pipeline",
    "get_active_pipeline": "pipeline",
    "CycleError": "pipeline",
    # Plugins
    "HookRegistry": "plugins",
    "function_to_schema": "schema",
    "validate_arguments": "schema",
    "MinLen": "schema",
    "MaxLen": "schema",
    "Gt": "schema",
    "Lt": "schema",
    "Ge": "schema",
    "Le": "schema",
    "Pattern": "schema",
    "Description": "schema",
    "Positional": "schema",
    "Option": "schema",
    # Theme
    "ThemeStyle": "theme",
    "ThemeProxy": "theme",
    "DEFAULT_THEME": "theme",
    "make_style_filter": "theme",
    "format_output": "output",
    "write_output": "output",
    "generate_llms_txt": "llms",
    # Commands v2 (resources, prompts)
    "ResourceDef": "commands",
    "PromptDef": "commands",
    # MCP Apps
    "MCP_APPS_EXTENSION_ID": "mcp_apps",
    "MCP_APPS_MIME_TYPE": "mcp_apps",
    "MCPAppCSP": "mcp_apps",
    "MCPAppPermissions": "mcp_apps",
    "MCPAppResourceDef": "mcp_apps",
    "MCPAppResourceMeta": "mcp_apps",
    "MCPAppToolMeta": "mcp_apps",
    "MCPAppVisibility": "mcp_apps",
    # Middleware
    "MCPCall": "middleware",
    "MiddlewareStack": "middleware",
    # Streaming
    "Progress": "streaming",
    # Observability
    "RequestLog": "observability",
    "RequestLogger": "observability",
    # Completions
    "install_completions": "completions",
    # Doctor
    "Check": "doctor",
    "DoctorReport": "doctor",
    "run_doctor": "doctor",
    "format_doctor_report": "doctor",
    # Reducer combinators
    "quit_on": "reducers",
    "with_cursor": "reducers",
    "with_confirm": "reducers",
    # Version check
    "VersionInfo": "version_check",
    "check_version": "version_check",
}


def __getattr__(name: str):
    """Lazy imports for public API."""
    if name in _LAZY_IMPORTS:
        import importlib

        module = importlib.import_module(f"milo.{_LAZY_IMPORTS[name]}")
        return getattr(module, name)
    raise AttributeError(f"module 'milo' has no attribute {name!r}")


# Free-threaded Python marker (PEP 703)
def _Py_mod_gil() -> int:  # noqa: N802
    return 0


__version__ = "0.4.3"
__all__ = [
    "BUILTIN_ACTIONS",
    "CLI",
    "DEFAULT_THEME",
    "MCP_APPS_EXTENSION_ID",
    "MCP_APPS_MIME_TYPE",
    "Action",
    "All",
    "App",
    "AppError",
    "AppStatus",
    "Batch",
    "CLIProgress",
    "Call",
    "Check",
    "Cmd",
    "CommandDef",
    "CommandSurface",
    "Config",
    "ConfigError",
    "ConfigSpec",
    "ConfirmStrategy",
    "Context",
    "CycleError",
    "Debounce",
    "Delay",
    "Description",
    "DevServer",
    "DoctorReport",
    "EffectResult",
    "ErrorCode",
    "FieldSpec",
    "FieldState",
    "FieldType",
    "Flow",
    "FlowError",
    "FlowScreen",
    "FlowState",
    "Fork",
    "FormError",
    "FormState",
    "Ge",
    "GlobalOption",
    "Group",
    "GroupDef",
    "Gt",
    "HelpRenderer",
    "HookRegistry",
    "InputError",
    "InvokeResult",
    "Key",
    "LazyCommandDef",
    "Le",
    "Lt",
    "MCPAppCSP",
    "MCPAppError",
    "MCPAppPermissions",
    "MCPAppResourceDef",
    "MCPAppResourceMeta",
    "MCPAppToolMeta",
    "MCPAppVisibility",
    "MCPCall",
    "MaxLen",
    "MiddlewareStack",
    "MiloError",
    "MinLen",
    "NullOutputSink",
    "Option",
    "OutputSink",
    "Pattern",
    "Phase",
    "PhaseLog",
    "PhasePolicy",
    "PhaseStatus",
    "Pipeline",
    "PipelineError",
    "PipelineState",
    "PipelineViewState",
    "PluginError",
    "Positional",
    "Progress",
    "PromptDef",
    "Put",
    "Quit",
    "Race",
    "ReducerResult",
    "RenderTarget",
    "RequestLog",
    "RequestLogger",
    "ResourceDef",
    "Retry",
    "RootOptionSpec",
    "SagaContext",
    "Screen",
    "Select",
    "Sequence",
    "SpecialKey",
    "StateError",
    "Store",
    "Take",
    "ThemeProxy",
    "ThemeStyle",
    "TickCmd",
    "Timeout",
    "Transition",
    "TryCall",
    "VersionInfo",
    "ViewState",
    "check_version",
    "combine_reducers",
    "compact_cmds",
    "form",
    "form_reducer",
    "form_schema",
    "format_doctor_report",
    "format_error",
    "format_output",
    "format_render_error",
    "function_to_schema",
    "generate_llms_txt",
    "get_active_pipeline",
    "get_context",
    "install_completions",
    "make_detail_reducer",
    "make_form_reducer",
    "make_style_filter",
    "pipeline_to_timeline",
    "quit_on",
    "render_html",
    "run",
    "run_doctor",
    "set_active_pipeline",
    "validate_arguments",
    "with_confirm",
    "with_cursor",
    "write_output",
]
