"""Milo — Template-driven CLI applications for free-threaded Python."""

from __future__ import annotations


def __getattr__(name: str):
    """Lazy imports for public API."""
    _imports = {
        # Types
        "Action": "_types",
        "Key": "_types",
        "SpecialKey": "_types",
        "AppStatus": "_types",
        "RenderTarget": "_types",
        "FieldType": "_types",
        "FieldSpec": "_types",
        "FieldState": "_types",
        "FormState": "_types",
        "Screen": "_types",
        "Transition": "_types",
        "ReducerResult": "_types",
        "Quit": "_types",
        "Call": "_types",
        "Put": "_types",
        "Select": "_types",
        "Fork": "_types",
        "Delay": "_types",
        "Retry": "_types",
        "Cmd": "_types",
        "Batch": "_types",
        "Sequence": "_types",
        "TickCmd": "_types",
        "ViewState": "_types",
        "compact_cmds": "_types",
        "BUILTIN_ACTIONS": "_types",
        # Errors
        "MiloError": "_errors",
        "InputError": "_errors",
        "StateError": "_errors",
        "FormError": "_errors",
        "AppError": "_errors",
        "FlowError": "_errors",
        "ConfigError": "_errors",
        "PipelineError": "_errors",
        "PluginError": "_errors",
        "ErrorCode": "_errors",
        "format_error": "_errors",
        "format_render_error": "_errors",
        # State
        "Store": "state",
        "combine_reducers": "state",
        # App
        "App": "app",
        "run": "app",
        "render_html": "app",
        # Flow
        "FlowScreen": "flow",
        "Flow": "flow",
        "FlowState": "flow",
        # Form
        "form": "form",
        "form_reducer": "form",
        "make_form_reducer": "form",
        # Help
        "HelpRenderer": "help",
        # Dev
        "DevServer": "dev",
        # Commands (AI-native)
        "CLI": "commands",
        "CommandDef": "commands",
        "LazyCommandDef": "commands",
        "InvokeResult": "commands",
        # Groups
        "Group": "groups",
        "GroupDef": "groups",
        "GlobalOption": "commands",
        # Context
        "Context": "context",
        "get_context": "context",
        "CLIProgress": "context",
        # Config
        "Config": "config",
        "ConfigSpec": "config",
        # Pipeline
        "Pipeline": "pipeline",
        "Phase": "pipeline",
        "PipelineState": "pipeline",
        "PhaseStatus": "pipeline",
        # Plugins
        "HookRegistry": "plugins",
        "function_to_schema": "schema",
        "MinLen": "schema",
        "MaxLen": "schema",
        "Gt": "schema",
        "Lt": "schema",
        "Ge": "schema",
        "Le": "schema",
        "Pattern": "schema",
        "Description": "schema",
        # Theme
        "ThemeStyle": "theme",
        "ThemeProxy": "theme",
        "DEFAULT_THEME": "theme",
        "make_style_filter": "theme",
        "format_output": "output",
        "write_output": "output",
        "generate_llms_txt": "llms",
        # Commands v2 (resources, prompts)
        "ResourceDef": "commands",
        "PromptDef": "commands",
        # Middleware
        "MCPCall": "middleware",
        "MiddlewareStack": "middleware",
        # Streaming
        "Progress": "streaming",
        # Observability
        "RequestLog": "observability",
        "RequestLogger": "observability",
        # Completions
        "install_completions": "completions",
        # Doctor
        "Check": "doctor",
        "DoctorReport": "doctor",
        "run_doctor": "doctor",
        "format_doctor_report": "doctor",
        # Reducer combinators
        "quit_on": "reducers",
        "with_cursor": "reducers",
        "with_confirm": "reducers",
        # Version check
        "VersionInfo": "version_check",
        "check_version": "version_check",
    }
    if name in _imports:
        import importlib

        module = importlib.import_module(f"milo.{_imports[name]}")
        return getattr(module, name)
    raise AttributeError(f"module 'milo' has no attribute {name!r}")


# Free-threaded Python marker (PEP 703)
def _Py_mod_gil() -> int:  # noqa: N802
    return 0


__version__ = "0.1.1"
__all__ = [
    "BUILTIN_ACTIONS",
    "CLI",
    "Action",
    "App",
    "AppError",
    "AppStatus",
    "Batch",
    "CLIProgress",
    "Call",
    "Check",
    "Cmd",
    "CommandDef",
    "Config",
    "ConfigError",
    "ConfigSpec",
    "Context",
    "Delay",
    "Description",
    "DevServer",
    "DoctorReport",
    "ErrorCode",
    "FieldSpec",
    "FieldState",
    "FieldType",
    "Flow",
    "FlowError",
    "FlowScreen",
    "FlowState",
    "Fork",
    "FormError",
    "FormState",
    "Ge",
    "GlobalOption",
    "Group",
    "GroupDef",
    "Gt",
    "HelpRenderer",
    "HookRegistry",
    "InputError",
    "InvokeResult",
    "Key",
    "LazyCommandDef",
    "Le",
    "Lt",
    "MCPCall",
    "MaxLen",
    "MiddlewareStack",
    "MiloError",
    "MinLen",
    "Pattern",
    "Phase",
    "PhaseStatus",
    "Pipeline",
    "PipelineError",
    "PipelineState",
    "PluginError",
    "Progress",
    "PromptDef",
    "Put",
    "Quit",
    "ReducerResult",
    "RenderTarget",
    "RequestLog",
    "RequestLogger",
    "ResourceDef",
    "Retry",
    "Screen",
    "Select",
    "Sequence",
    "SpecialKey",
    "StateError",
    "Store",
    "ThemeProxy",
    "ThemeStyle",
    "TickCmd",
    "Transition",
    "VersionInfo",
    "ViewState",
    "check_version",
    "combine_reducers",
    "compact_cmds",
    "form",
    "form_reducer",
    "format_doctor_report",
    "format_error",
    "format_output",
    "format_render_error",
    "function_to_schema",
    "generate_llms_txt",
    "get_context",
    "DEFAULT_THEME",
    "install_completions",
    "make_form_reducer",
    "make_style_filter",
    "quit_on",
    "render_html",
    "run",
    "run_doctor",
    "with_confirm",
    "with_cursor",
    "write_output",
]
